name: Run tests

on: 
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test

  manual-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
      
    - name: Run tests manually
      run: npm test
